server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airsync_bookings
    username: postgres
    password: 1212
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: airsync.exchange
  routing-key: booking.events
  queue: booking.notification.queue
